import = [
    "~/.config/alacritty/themes/catppuccin.toml"
]
[window]
decorations = "None"

[font]
normal.family = "DaddyTimeMono Nerd Font"
normal.style = "Regular"
size = 9
offset.x = -1
offset.y = -1

[colors]
draw_bold_text_with_bright_colors = true
